---
substitutions:
  device_name: watermeter

esp8266:
  board: d1_mini_pro
  framework:
    version: recommended

esphome:
  name: ${device_name}
  project:
    name: breaveheard.watermeter
    version: "2.7"

wifi:
  ap:
    ssid: "Water-Meter Fallback Hotspot"
    password: "12345678"  # Required in newer versions for security

captive_portal:

logger:

api:

ota:
  platform: esphome
  
improv_serial:

web_server:
  port: 80
  
dashboard_import:
  package_import_url: github://Breaveheard/esphome-watermeter/watermeter.yaml@main
  import_full_config: true

debug:

text_sensor:
  - platform: version
    name: Water-Meter ESPHome Version
  - platform: wifi_info
    ip_address:
      name: Water-Meter IP
    ssid:
      name: Water-Meter SSID
    bssid:
      name: Water-Meter BSSID

globals:
  - id: total_pulses
    type: int
    restore_value: true
    initial_value: '0'  # startet mit 0
  - id: imp_ratio
    type: float
    restore_value: false
    initial_value: '0.01'  # 10 Liter pro Impuls = 0.01 m³
  - id: initial_consumption
    type: float
    restore_value: false
    initial_value: '0'  # in m³

binary_sensor:
  - platform: gpio
    id: internal_pulse_counter
    pin:
      number: GPIO2  # D4 is GPIO2 on ESP8266, using GPIO number is preferred
      mode: INPUT_PULLUP
    name: "Live-Impuls"
    filters:
      - delayed_on: 100ms
    on_press:
      then:
        - lambda: id(total_pulses) += 1;

  - platform: status
    name: "Status Water-Meter"
    entity_category: diagnostic

sensor:
  - platform: template
    name: "Wasserverbrauch"
    device_class: water
    update_interval: 10s
    unit_of_measurement: "m³"
    state_class: total_increasing
    icon: "mdi:water"
    accuracy_decimals: 2
    lambda: return id(initial_consumption) + (id(total_pulses) * id(imp_ratio));

  - platform: template
    name: "Pulse Counter total"
    update_interval: 10s
    icon: "mdi:counter"
    accuracy_decimals: 0
    unit_of_measurement: "pulses"
    lambda: return id(total_pulses);

